CREATE SCHEMA CS470_GROUP_PROJECT;
USE CS470_GROUP_PROJECT;

CREATE TABLE CUSTOMER (
	FIRST VARCHAR(20) NOT NULL,
    LAST VARCHAR(20) NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_METHOD VARCHAR(30) NOT NULL,
    TIME_PURCHASED INT NOT NULL,
    FINAL_FEE INT,
    
    PRIMARY KEY (CUSTOMER_ID)
);
    
CREATE TABLE PARKING_SPACE (
	SPACE_NUMBER INT NOT NULL,
    FLOOR INT NOT NULL,
    LOT INT NOT NULL,
    COST INT,
    AVAILABLE BIT,
    REQUIRE_PASS BIT,
    DISABLED BIT,
    DISCOUNTED BIT,
    
    PRIMARY KEY (LOT, FLOOR, SPACE_NUMBER)
);

CREATE TABLE SPACE_ASSIGNED (
	CUSTOMER_ID INT NOT NULL,
    SPACE_NUMBER INT NOT NULL,
	FLOOR INT NOT NULL,
	LOT INT NOT NULL,
    
    PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT FK_LFSN_PARKINGSPACE FOREIGN KEY (LOT, FLOOR, SPACE_NUMBER) REFERENCES PARKING_SPACE (LOT, FLOOR, SPACE_NUMBER),
    CONSTRAINT FK_CID_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE PARKING_LOT (
	LOT_NUMBER INT NOT NULL,
	MAX_FLOORS INT NOT NULL,
    TOTAL_SPACES INT NOT NULL,
    
    PRIMARY KEY (LOT_NUMBER)
);

ALTER TABLE PARKING_SPACE ADD CONSTRAINT FK_LOTNUMBER_LOT FOREIGN KEY (LOT) REFERENCES PARKING_LOT (LOT_NUMBER);
ALTER TABLE SPACE_ASSIGNED ADD CONSTRAINT FK_LOTNUMBER_LOT FOREIGN KEY (LOT) REFERENCES PARKING_LOT (LOT_NUMBER);